name: TypeORM migration

on: 
  push:
    branches: [ main ]

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - run: npm run typeorm:generate src/migrations
      - run: npm run typeorm migration:run
      
